---
title: Tugas Eigenvalue dan Eigenvector
---

## 1. Import Library NumPy

NumPy merupakan pustaka (*library*) fundamental dalam pemrograman Python yang digunakan untuk komputasi numerik, khususnya pengolahan array multidimensi dan operasi aljabar linear. Pustaka ini diimpor sebagai prasyarat utama untuk mendukung efisiensi komputasi numerik dalam pengolahan matriks.

In [1]:
import numpy as np

## 2. Ortogonalisasi Gram-Schmidt dan Dekomposisi QR

Algoritma Gram-Schmidt merupakan metode sistematis untuk membangun sekumpulan vektor ortonormal dari sekumpulan vektor yang bebas linear. Dalam konteks faktorisasi $QR$, algoritma ini digunakan untuk memecah matriks persegi $A$ menjadi produk dari matriks ortogonal $Q$ dan matriks segitiga atas $R$ ($A = QR$). Proses ini sangat penting karena matriks ortogonal memenuhi sifat $Q^T Q = I$ yang mempermudah proses komputasi numerik.

In [2]:
def gram_schmidt(A):
    A = np.array(A, dtype=float)

    n = A.shape[1]

    Q = np.zeros_like(A, dtype=float)
    R = np.zeros((n, n), dtype=float)

    for j in range(n):
        # Pengambilan kolom ke-j dari matriks A
        v = A[:, j]

        # Proses ortogonalisasi dengan mengurangi proyeksi terhadap basis ortogonal sebelumnya
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])

            v = v - R[i, j] * Q[:, i]

        # Normalisasi vektor hasil ortogonalisasi menjadi vektor satuan (ortonormal)
        R[j, j] = np.linalg.norm(v)

        Q[:, j] = v / R[j, j]

    return Q, R

## 3. Algoritma Iterasi QR untuk Estimasi Nilai Eigen

Iterasi QR merupakan salah satu metode numerik yang efisien untuk memperkirakan seluruh nilai eigen (*eigenvalues*) dari matriks persegi. Algoritma ini memfaktorkan matriks $A_k$ menjadi $Q_k R_k$ pada setiap iterasi $k$, kemudian membentuk matriks berikutnya melalui perkalian terbalik: $A_{k+1} = R_k Q_k$.

Karena $A_{k+1} = R_k Q_k = Q_k^T A_k Q_k$, matriks $A_{k+1}$ bersifat serupa (*similar*) dengan $A_k$, sehingga memiliki nilai eigen yang identik. Seiring bertambahnya iterasi, matriks $A_k$ akan konvergen menuju bentuk segitiga atas, di mana entri-entri diagonal utamanya merepresentasikan seluruh nilai eigen dari matriks asal $A$.

In [3]:
def qr_iteration(A, iterations=10):
    A_k = np.array(A, dtype=float)

    for k in range(iterations):
        print(f"\n=== Iterasi {k+1} ===")

        # Melakukan dekomposisi QR menggunakan metode Gram-Schmidt
        Q, R = gram_schmidt(A_k)

        print("\nQ:")
        print(Q)

        print("\nR:")
        print(R)

        # Rekonstruksi matriks baru melalui perkalian terbalik A_(k+1) = R_k * Q_k
        A_k = R @ Q

        print("\nA baru:")
        print(A_k)

    return A_k

## 4. Simulasi Komputasi dan Verifikasi Hasil

Untuk menguji keandalan algoritma iterasi QR yang telah dibangun, dilakukan simulasi menggunakan matriks simetris berordo $2 \times 2$:

$$A = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}$$

Secara teoretis, nilai eigen dari matriks simetris $A$ tersebut dapat dihitung melalui persamaan karakteristik $\det(A - \lambda I) = 0$, yang menghasilkan nilai eigen $\lambda_1 = 3$ dan $\lambda_2 = 1$. Di bawah ini iterasi dijalankan sebanyak 10 kali untuk mengamati tingkat konvergensinya.

In [4]:
A = np.array([
    [2, 1],
    [1, 2]
], dtype=float)

hasil = qr_iteration(A, iterations=10)

print("Hasil Akhir:")
print(hasil)

print("\nPerkiraan Eigenvalue:")
print(np.diag(hasil))


=== Iterasi 1 ===

Q:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

R:
[[2.23606798 1.78885438]
 [0.         1.34164079]]

A baru:
[[2.8 0.6]
 [0.6 1.2]]

=== Iterasi 2 ===

Q:
[[ 0.97780241 -0.20952909]
 [ 0.20952909  0.97780241]]

R:
[[2.86356421 0.83811635]
 [0.         1.04764544]]

A baru:
[[2.97560976 0.2195122 ]
 [0.2195122  1.02439024]]

=== Iterasi 3 ===

Q:
[[ 0.99729001 -0.07357057]
 [ 0.07357057  0.99729001]]

R:
[[2.98369553 0.2942823 ]
 [0.         1.00546452]]

A baru:
[[2.99726027 0.0739726 ]
 [0.0739726  1.00273973]]

=== Iterasi 4 ===

Q:
[[ 0.99969559 -0.02467256]
 [ 0.02467256  0.99969559]]

R:
[[2.99817296 0.09869024]
 [0.         1.00060938]]

A baru:
[[2.99969521 0.0246876 ]
 [0.0246876  1.00030479]]

=== Iterasi 5 ===

Q:
[[ 0.99996613 -0.00822976]
 [ 0.00822976  0.99996613]]

R:
[[2.9997968  0.03291902]
 [0.         1.00006774]]

A baru:
[[2.99996613 0.00823031]
 [0.00823031 1.00003387]]

=== Iterasi 6 ===

Q:
[[ 0.99999624 -0.00274346]
 [ 0.00274346

## 5. Pengenalan dan Pembuktian Vektor Eigen (Eigenvector)

Setelah mendapatkan nilai eigen (*eigenvalues*) dari matriks $A$, langkah krusial berikutnya adalah menentukan vektor eigen (*eigenvectors*) yang berkorespondensi.

### **Definisi Geometris dan Matematis**
Secara geometris, vektor eigen adalah vektor non-nol $\vec{v}$ yang ketika ditransformasikan oleh matriks $A$, arahnya **tidak mengalami perubahan** (hanya mengalami penskalaan atau perubahan panjang). Faktor skala perubahan panjang tersebut merupakan nilai eigen $\lambda$ yang bersesuaian.

Hubungan fundamental ini dinyatakan dalam persamaan karakteristik:

$$A \vec{v} = \lambda \vec{v}$$

Berikut merupakan pembuktian numerik untuk memverifikasi identitas matematis tersebut menggunakan hasil komputasi pustaka NumPy (`np.linalg.eig`).

In [ ]:
# 1. Menghitung nilai eigen dan vektor eigen menggunakan fungsi bawaan NumPy
eigenvalues, eigenvectors = np.linalg.eig(A)

print("=== Hasil Perhitungan NumPy ===")
for i in range(len(eigenvalues)):
    print(f"\nPasangan Eigen ke-{i+1}:")
    print(f"  - Nilai Eigen (lambda_{i+1}) : {eigenvalues[i]:.4f}")
    print(f"  - Vektor Eigen (v_{i+1})      : {eigenvectors[:, i]}")

print("\n=== Pembuktian Hubungan A * v = lambda * v ===")
# Pengambilan pasangan eigen pertama untuk diuji dan diverifikasi
lambda_1 = eigenvalues[0]
v_1 = eigenvectors[:, 0]

# Perhitungan ruas kiri persamaan: Perkalian matriks A dengan vektor eigen v_1
sisi_kiri = A @ v_1

# Perhitungan ruas kanan persamaan: Perkalian skalar lambda_1 dengan vektor eigen v_1
sisi_kanan = lambda_1 * v_1

print(f"Vektor v_1                     : {v_1}")
print(f"Sisi Kiri (A * v_1)            : {sisi_kiri}")
print(f"Sisi Kanan (lambda_1 * v_1)    : {sisi_kanan}")
print(f"Apakah Sisi Kiri = Sisi Kanan? : {np.allclose(sisi_kiri, sisi_kanan)}")