---
title: Implementasi Eigenvalue
date: 2026-05-12
---

# Import Library NumPy

Pada bagian ini, kita mengimpor library NumPy yang merupakan fundamental untuk komputasi numerik dalam Python. NumPy menyediakan dukungan untuk array multidimensi dan berbagai fungsi matematika yang akan kita gunakan untuk implementasi algoritma $eigenvalue$.

In [7]:
import numpy as np

# Implementasi Algoritma Gram-Schmidt

Pada bagian ini, kita mengimplementasikan algoritma Gram-Schmidt yang merupakan metode fundamental untuk dekomposisi $QR$. Algoritma ini bekerja dengan mengubah sekumpulan vektor yang saling bebas menjadi sekumpulan vektor yang ortonormal. Proses ini sangat penting dalam faktorisasi $QR$ dimana matriks $A$ dipecah menjadi produk matriks ortogonal $Q$ dan matriks segitiga atas $R$.

In [8]:
def gram_schmidt(A):
    A = np.array(A, dtype=float)

    n = A.shape[1]

    Q = np.zeros_like(A, dtype=float)
    R = np.zeros((n, n), dtype=float)

    for j in range(n):
        # Ambil kolom ke-j
        v = A[:, j]

        # Kurangi proyeksi terhadap q sebelumnya
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])

            v = v - R[i, j] * Q[:, i]

        # Normalisasi
        R[j, j] = np.linalg.norm(v)

        Q[:, j] = v / R[j, j]

    return Q, R

# Implementasi Iterasi QR

Pada bagian ini, kita mengimplementasikan algoritma iterasi $QR$ untuk mencari nilai eigen ($eigenvalue$) dari suatu matriks. Algoritma ini bekerja dengan melakukan faktorisasi $QR$ secara berulang pada matriks $A$. Pada setiap iterasi, matriks $A_k$ dipecah menjadi $Q_k$ dan $R_k$, kemudian matriks baru $A_{k+1}$ dibentuk dengan mengalikan $R_k$ dengan $Q_k$. Proses ini diulang hingga matriks konvergen ke bentuk segitiga atas yang elemen diagonalnya merupakan nilai eigen dari matriks asli.

In [9]:
def qr_iteration(A, iterations=10):
    A_k = np.array(A, dtype=float)

    for k in range(iterations):
        print(f"\n=== Iterasi {k+1} ===")

        # Faktorisasi QR
        Q, R = gram_schmidt(A_k)

        print("\nQ:")
        print(Q)

        print("\nR:")
        print(R)

        # A_(k+1) = RQ
        A_k = R @ Q

        print("\nA baru:")
        print(A_k)

    return A_k

# Contoh Implementasi dan Hasil

Pada bagian ini, kita menerapkan algoritma iterasi $QR$ pada contoh matriks $2 \times 2$ sederhana. Matriks yang digunakan adalah $[[2, 1], [1, 2]]$ yang merupakan matriks simetris. Kita melakukan 10 iterasi untuk menunjukkan konvergensi algoritma. Hasil akhir yang diharapkan adalah matriks segitiga atas dengan nilai eigen pada diagonalnya. Untuk matriks ini, nilai eigen yang diharapkan adalah 3 dan 1.

In [10]:
A = np.array([
    [2, 1],
    [1, 2]
], dtype=float)

hasil = qr_iteration(A, iterations=10)

print("Hasil Akhir:")
print(hasil)

print("\nPerkiraan Eigenvalue:")
print(np.diag(hasil))


=== Iterasi 1 ===

Q:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

R:
[[2.23606798 1.78885438]
 [0.         1.34164079]]

A baru:
[[2.8 0.6]
 [0.6 1.2]]

=== Iterasi 2 ===

Q:
[[ 0.97780241 -0.20952909]
 [ 0.20952909  0.97780241]]

R:
[[2.86356421 0.83811635]
 [0.         1.04764544]]

A baru:
[[2.97560976 0.2195122 ]
 [0.2195122  1.02439024]]

=== Iterasi 3 ===

Q:
[[ 0.99729001 -0.07357057]
 [ 0.07357057  0.99729001]]

R:
[[2.98369553 0.2942823 ]
 [0.         1.00546452]]

A baru:
[[2.99726027 0.0739726 ]
 [0.0739726  1.00273973]]

=== Iterasi 4 ===

Q:
[[ 0.99969559 -0.02467256]
 [ 0.02467256  0.99969559]]

R:
[[2.99817296 0.09869024]
 [0.         1.00060938]]

A baru:
[[2.99969521 0.0246876 ]
 [0.0246876  1.00030479]]

=== Iterasi 5 ===

Q:
[[ 0.99996613 -0.00822976]
 [ 0.00822976  0.99996613]]

R:
[[2.9997968  0.03291902]
 [0.         1.00006774]]

A baru:
[[2.99996613 0.00823031]
 [0.00823031 1.00003387]]

=== Iterasi 6 ===

Q:
[[ 0.99999624 -0.00274346]
 [ 0.00274346